### ISSUE TITLE
Start using coveralls.io

### ISSUE THREAD

**Issue by zeroXten** [pki-io/core#25]
Shows code coverage

**Comment by zeroXten** [comment]
Would be quite funny to see how bad our coverage is :D

**Comment by thanasisk** [comment]
Well, you have to start someplace ...

**Comment by jonbonazza** [comment]
If you are curious,  you can use go test --coverprofile=/tmp/cov.

**Comment by jonbonazza** [comment]
After you run the above command,  you can run go tool cover --html=/tmp/cov

To see what is covered and what isn't

**Comment by jonbonazza** [comment]
The crypto package isn't half bad. Here's the result:
```
$ go test --coverprofile=/tmp/cov
PASS
coverage: 81.9% of statements
ok  	github.com/pki-io/pki.io/crypto	13.653s
```

**Comment by jonbonazza** [comment]
The total result is a bit crappy, thought:

```
$ go test -cover ./...
ok  	github.com/pki-io/pki.io/config	0.003s	coverage: 69.4% of statements
ok  	github.com/pki-io/pki.io/crypto	8.878s	coverage: 81.9% of statements
ok  	github.com/pki-io/pki.io/document	0.002s	coverage: 22.1% of statements
ok  	github.com/pki-io/pki.io/entity	8.258s	coverage: 55.6% of statements
ok  	github.com/pki-io/pki.io/fs	0.005s	coverage: 35.3% of statements
ok  	github.com/pki-io/pki.io/index	0.010s	coverage: 80.4% of statements
ok  	github.com/pki-io/pki.io/node	0.220s	coverage: 39.7% of statements
ok  	github.com/pki-io/pki.io/x509	0.023s	coverage: 71.4% of statements
```

Averagin all of those up, you get a grand total coverage of only 61.95%. A few of those packages can be upped quite a bit thought. =)

**Comment by thanasisk** [comment]
so are we using coveralls.io or not?

**Comment by jonbonazza** [comment]
I think it would make things easier to calculate, so I am all for it. Was just curious what our coverage was, so I checked it out.

**Comment by thanasisk** [comment]
thanks for the clarification - I will try to find some time to sort it out tomorrow morning.
