### ISSUE TITLE
ECIES error

### ISSUE THREAD

**Issue by zeroXten** [pki-io/core#46]
Just got a random one-off error

[file-structure][fscott@ukm043583 test-org]$ gom run ../*.go node new server1 --pairing-id 6f18aad6be59961dd81695686d1f7c5b --pairing-key a88077882a6bc6d6ed9997b21deb8593
Loading admin app
Loading admin entity
Loading org entity
Creating new node
Generating node keys
Encrypting node for org
Could encrypt and authenticate node: Couldn't encrypt content: Could not encrypt container: Could not group encrypt: ecies: shared key is too big:
panic: Could encrypt and authenticate node: Couldn't encrypt content: Could not encrypt container: Could not group encrypt: ecies: shared key is too big:
...

Running the same command again worked.

**Comment by jonbonazza** [comment]
Interesting... Ill have to look into it.

**Comment by zeroXten** [comment]
just caused this again after running "make test" a few times.

**Comment by jonbonazza** [comment]
Interesting. So can i reproduce this if i spam make test?

**Comment by zeroXten** [comment]
I presume so.

**Comment by zeroXten** [comment]
Raised this here after reproducing it with stripped down test code: https://github.com/obscuren/ecies/issues/4

**Comment by zeroXten** [comment]
Upstream fixed this in Feb. I have updated our fork to the current master.
